//Showtime
export const GET_LIST_MOVIES_COMMING = "GET_LIST_MOVIES_COMMING";
export const GET_LIST_MOVIES_SHOWING = "GET_LIST_MOVIES_SHOWING";
export const GET_LIST_MOVIES = "GET_LIST_MOVIES";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
//Theatres
export const GET_LIST_SYSTEM_THEATRES = "GET_LIST_SYSTEM_THEATRES";
export const GET_DETAIL_BRANCH_THEATRES = "GET_DETAIL_BRANCH_THEATRES";
export const SET_ACTIVE_LOGO = "SET_ACTIVE_LOGO";
export const SET_ACTIVE_BRANCH = "SET_ACTIVE_BRANCH";
export const SET_ACTIVE_LISTMOVIE = "SET_ACTIVE_LISTMOVIE";
export const GET_SYSTEM_THEATRES = "GET_SYSTEM_THEATRES";
