export const GET_LIST_MOVIES_COMMING = "GET_LIST_MOVIES_COMMING";
export const GET_LIST_MOVIES_SHOWING = "GET_LIST_MOVIES_SHOWING";
export const GET_LIST_MOVIES = "GET_LIST_MOVIES";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";

export const GET_LIST_LOGO_THEATRES = "GET_LIST_LOGO_THEATRES";